version: "3.8"

services:
  dk_nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dk_nifi
    restart: always
    ports:
      - 8182:8182
    environment:
      - NIFI_WEB_HTTP_PORT=8182
    # if your cert is self signed and has a domain name in it, add domain name as extrahost  
    extra_hosts:
      - "<your domain name here>:<your id here>"
    volumes:
      - dk_nifi_state:/opt/nifi/nifi-current/state
      - dk_nifi_db:/opt/nifi/nifi-current/database_repository
      - dk_nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - dk_nifi_content:/opt/nifi/nifi-current/content_repository
      - dk_nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - dk_nifi_logs:/opt/nifi/nifi-current/logs
      - dk_nifi_conf:/opt/nifi/nifi-current/conf
volumes:
  dk_nifi_state:
  dk_nifi_db:
  dk_nifi_flowfile:
  dk_nifi_content:
  dk_nifi_provenance:
  dk_nifi_logs:
  dk_nifi_conf:
  
  
  